name: Build, Push to ACR, and Deploy to App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      IMAGE_NAME: weathertracker-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name "$ACR_NAME"

      - name: Set image tag
        id: vars
        run: |
          IMAGE_TAG=${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push to ACR
        run: |
          IMAGE_TAG=${{ steps.vars.outputs.IMAGE_TAG }}

          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            docker tag $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
            docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
          fi

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: weathertracker01
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG }}
